### ISSUE TITLE
rmrk collection id

### ISSUE THREAD

**Issue by 123oli** [rmrk-team/rmrk-ink#29]
[collection_id](https://github.com/rmrk-team/rmrk-ink/blob/4e9d42db0e685b13cce52edb26af01d919fe5e78/contracts/rmrk/lib.rs#L220) in `rmrk constructor`, Is it from [UtilsData::collection_id](https://github.com/rmrk-team/rmrk-ink/blob/4e9d42db0e685b13cce52edb26af01d919fe5e78/logics/impls/rmrk/types.rs#L53)? When it change? I found [last_token_id](https://github.com/rmrk-team/rmrk-ink/blob/4e9d42db0e685b13cce52edb26af01d919fe5e78/logics/impls/rmrk/types.rs#L60) increment while minting token.

**Comment by Maar-io** [comment]
Sorry, this is not an issue. Please open issues if you see problems or have comment on the implementation. Not for a random questions.

`Collection_Id` is a unique identifier per contract. It is used as argument in some of the functions.
`last_token_id` is unrelated to collection_id. It is counter for minting tokens
