### ISSUE TITLE
Differents between Asset vs ChildNft

### ISSUE THREAD

**Issue by 123oli** [rmrk-team/rmrk-ink#30]
In [`add_asset_to_token`](https://github.com/rmrk-team/rmrk-ink/blob/4e9d42db0e685b13cce52edb26af01d919fe5e78/logics/impls/rmrk/multiasset.rs#L246) function what does `asset` represents? Is it same like `ChildNft`? [add_child](https://github.com/rmrk-team/rmrk-ink/blob/4e9d42db0e685b13cce52edb26af01d919fe5e78/logics/impls/rmrk/nesting.rs#L231) function `add_child to parent_token_id` and add_asset_to_token function `add_asset to token_id`. Is token_id in `add_asset same as parent_token_id` in add_child?

**Comment by Maar-io** [comment]
Perhaps you can read what is Asset in RMRK (previously called resources) 
* RMRK [Asset](https://github.com/rmrk-team/MultiResourceEIP)

And what is childNft
* RMRK [Nesting](https://github.com/rmrk-team/NestingEIP)

**Comment by Maar-io** [comment]
This is not an issue. Please also check the test/ to learn how this works
