### ISSUE TITLE
Implement cross contract check to validate equipping child

### ISSUE THREAD

**Issue by Maar-io** [rmrk-team/rmrk-ink#33]
Before equipping an asset ensure that token_can_be_equipped_with_asset_into_slot
This will break part of unitests for `equip`.

- [ ] Make cross contract call in equip() function to call `ensure_token_can_be_equipped_with_asset_into_slot()`
- [ ] Fix part of the unit test that will be broken with this PR
- [ ] Introduce missing e2e test to cover equip. Perhaps new file `tests/equip.spec.ts`

We don't need to make it possible for an already existing PSP34 to be equipped. It would open doors to non sense equippings. If we can assume that child is always an implementer of equippable, then we can check safely.

**Comment by Szegoo** [comment]
@Maar-io Is this free to work on? If so I would like to implement this.

**Comment by Maar-io** [comment]
@boyswan Have you started on this? If not, Sergej can take it

**Comment by boyswan** [comment]
Haven't looked at this yet, @Szegoo feel free to go for it!
