### ISSUE TITLE
Ideas and improvements around rmrk-ink

### ISSUE THREAD

**Issue by boyswan** [rmrk-team/rmrk-ink#40]
I've been starting to experiment with `rmrk-ink` usage from another smart contract, and have had some initial thoughts around the current implementation as well as some rough ideas on how we can improve the library. 

It would be great to have a discussion as to whether any of these are worth looking further into. 

---

- ### Decouple underlying PSP34 implementation from contract logic
Currently the lib is heavily tied to the Openbrush `PSP34` implementation, but due to the volatility in establishing NFT standards and norms in dotsama, flexibility in providing different underlying implementations could be very useful. For example we could choose to support `uniques-v2 (chain-ext)`, `pallet_assets (if theres an equivalent for psp34?)`, `rmrk-pallets (chain-ext)` or anything new as alternative backends. 

I don't think this is a difficult change to make, but it will require some generalisation of a few areas. I've got a **_very rough_** idea of how this might look in [this branch](https://github.com/rmrk-team/rmrk-ink/tree/feature/decouple-psp34). Areas that need further generalising are errors (everything is a PSP34 error), which may actually justify the need for more [flexible error handling ](https://github.com/rmrk-team/rmrk-ink/tree/refactor/error-handling). Also need to consider how to select the implementation (ie. cargo flags etc).

---

- ### Move from `Ownable` to `AccessControl` ownership model
In its current state, the lib has the notion of a single owner. This is not flexible enough if we want the ability to compose multiple 'logic' smart contracts (or even users), and grant them minting rights. The `EVM` implementation also has the notion of `contributor` for their access control, which is something we could move towards. This should be a fairly straightforward improvement by utilising the Openbrush AccessControl lib.

---

- ### Distinction between "Ready to use" and "General use" implementations
Currently the logic provides both `mint-to-caller` and `only-owner-mint` which cater to different use-cases (self-minting vs controlled-minting), but not necessarily both at the same time. For example if I wanted a RMRK collection to be solely controlled by another ink! contract (ie. a game with extra logic), the `mint-to-caller` method is problematic. In the EVM implementation, "Lazy Minting" is an optional feature. Perhaps @steven2308 can provide some clarity on this design in the EVM lib incase I have misunderstood? My understanding is based off [this explanation](https://youtu.be/Bim0D-MVoVw?t=252).

---

Edit: added other findings to the list for us to discuss.

**Comment by Maar-io** [comment]
Thanks for coming up with these proposals!!! Here are couple of comments.
* PSP34
   * I agree that decoupling is good idea, but for a start I'd like to tests and release 1.0.0 with PSP34 interface
* uniques-v2  + chain-ext for it
   * This is next step but it requires that any chain using RMRK-ink needs to have this pallet and extension
* RMRK pallets
   * same comment as for Uniquest v2
   * I do not see point in RMRK-ink supporting RMRK pallets (Which btw rely on pallet-uniques)
___
I think we agreed to go with Error refactoring. I'll comment on PR #39 
___
Implement AccessControl: OK

**Comment by boyswan** [comment]
Agreed, PSP34 should be the focus for v1.0.0, decoupling the logic shouldn't get in the way of that.

I've also added another point on the list above to discuss. I'm aware these may not be priority for v1.0.0, but it might be worth thinking about them early on incase they change any fundamentals of the lib design!

**Comment by steven2308** [comment]
> Distinction between "Ready to use" and "General use" implementations
About this, I think it's something critical we should aim to. You got it right @boyswan. 

On EVM we have what we call *Core* implementations, which I think you refer to as "General Use". These are non opinionated, so methods as minting, burning and adding assets are up to the final implementer to define. We do provide internal non gated functions for each of those functionalities, so the custom implementations just need to define the permissions and call the internal function.

Then we have a series of *Ready-to*-use implementations (preminting, lazy minting with ERC20 and lazy minting with native token). These are opinionated and work with no extra changes needed, but users can still build more functionality on top.

The ready to use versions are for the less experienced developer and for simpler use cases. For advanced functionality we need the core versions. We expect both to be needed.
